### ISSUE TITLE
GLM structure

### ISSUE THREAD

**Issue by nghuyong** [BrightXiaoHan/fast-chatglm#1]
GLM is not a decoder only model, so it also need to convert encoder.

**Comment by BrightXiaoHan** [comment]
但是我看GLM可以以纯decoder的方式运行，这里也有个参数
![image](https://github.com/BrightXiaoHan/fast-chatglm/assets/25839309/2a2a7af5-dfcf-4415-b4cf-4eae030c3c44)

**Comment by BrightXiaoHan** [comment]
我仔细看了下源码，源码里只有self attention，没有cross attention，prefix-encoder是加载ptuning参数用的。encoder+decoder模式是通过attention mask模拟的。

**Comment by nghuyong** [comment]
原来如此
